### ISSUE TITLE
Compilation Failure with runExternalAnnotatorsWebserver.sh

### ISSUE THREAD

**Issue by munkeyt** [allenai/semanticilp#4]
I have successfully launched the *CogCompNLP* annotation server according to your instructions but I am facing some problems launching the external annotation server. It throws the error below:
```{bash}
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ExternalAnnotators: A suite of external annotators 3.1.22
[INFO] ------------------------------------------------------------------------
Downloading: http://cogcomp.cs.illinois.edu/m2repo/edu/cmu/cs/ark/ChuLiuEdmonds/1.0-SNAPSHOT/maven-metadata.xml
983 B   
        
Downloaded: http://cogcomp.cs.illinois.edu/m2repo/edu/cmu/cs/ark/ChuLiuEdmonds/1.0-SNAPSHOT/maven-metadata.xml (983 B at 0.5 KB/sec)
[WARNING] The POM for edu.illinois.cs.cogcomp:illinois-prepsrl-model:jar:3.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ illinois-external-annotators ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /data/cogcomp-nlp-3.1.22/external/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ illinois-external-annotators ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 16 source files to /data/cogcomp-nlp-3.1.22/external/target/classes
[INFO] /data/cogcomp-nlp-3.1.22/external/src/main/java/edu/illinois/cs/cogcomp/pipeline/handlers/PathLSTMHandler.java: Some input files use unchecked or unsafe operations.
[INFO] /data/cogcomp-nlp-3.1.22/external/src/main/java/edu/illinois/cs/cogcomp/pipeline/handlers/PathLSTMHandler.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /data/cogcomp-nlp-3.1.22/external/src/main/java/edu/illinois/cs/cogcomp/pipeline/handlers/PathLSTMHandler.java:[127,65] cannot find symbol
  symbol:   method getConstituentsWithSpan(edu.illinois.cs.cogcomp.core.datastructures.IntPair)
  location: variable pav of type edu.illinois.cs.cogcomp.core.datastructures.textannotation.PredicateArgumentView
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.720 s
[INFO] Finished at: 2018-07-13T02:54:23+00:00
[INFO] Final Memory: 49M/1588M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project illinois-external-annotators: Compilation failure
[ERROR] /data/cogcomp-nlp-3.1.22/external/src/main/java/edu/illinois/cs/cogcomp/pipeline/handlers/PathLSTMHandler.java:[127,65] cannot find symbol
[ERROR] symbol:   method getConstituentsWithSpan(edu.illinois.cs.cogcomp.core.datastructures.IntPair)
[ERROR] location: variable pav of type edu.illinois.cs.cogcomp.core.datastructures.textannotation.PredicateArgumentView
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project illinois-external-annotators: Compilation failure
/data/cogcomp-nlp-3.1.22/external/src/main/java/edu/illinois/cs/cogcomp/pipeline/handlers/PathLSTMHandler.java:[127,65] cannot find symbol
  symbol:   method getConstituentsWithSpan(edu.illinois.cs.cogcomp.core.datastructures.IntPair)
  location: variable pav of type edu.illinois.cs.cogcomp.core.datastructures.textannotation.PredicateArgumentView

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/data/cogcomp-nlp-3.1.22/external/src/main/java/edu/illinois/cs/cogcomp/pipeline/handlers/PathLSTMHandler.java:[127,65] cannot find symbol
  symbol:   method getConstituentsWithSpan(edu.illinois.cs.cogcomp.core.datastructures.IntPair)
  location: variable pav of type edu.illinois.cs.cogcomp.core.datastructures.textannotation.PredicateArgumentView

	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:972)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
It seems to have problem finding some object classes. Is there anything missing?

**Comment by danyaljj** [comment]
Sorry for the delay. 

Do we a favor: 

Try this and tell me what do you see in the output of each of the following commands: 
```
> mvn install -Dmaven.test.skip=true
> mvn compile 
```

If both are successfull, give another try to the external annotators' script.

**Comment by maticbizjak** [comment]
I faced the same problem. After running those two commands I got a different error:

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project illinois-external-annotators: An exception occured while executing the Java class. File is already opened and is locked: annotation-cache

All I had to do was remove the file and external annotators' script worked.

**Comment by danyaljj** [comment]
Cool. I hope it works fine for you now.
